import { useEffect, useState } from 'react';
import { api, getErrorMessage } from '@/api/client';
import type { AccessibilityDescriptionOut } from '@/api/types';
import {
  FileText,
  Save,
  Loader2,
  ShieldCheck,
  CheckCircle,
} from 'lucide-react';

interface AccessibilityEditorProps {
  artifactKind: 'patch' | 'piece' | 'sonification' | 'listening_session';
  artifactId: string;
  showToast: (msg: string) => void;
}

export default function AccessibilityEditor({
  artifactKind,
  artifactId,
  showToast,
}: AccessibilityEditorProps) {
  const [desc, setDesc] = useState<AccessibilityDescriptionOut | null>(null);
  const [editedText, setEditedText] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  // Fetch active accessibility transcript
  useEffect(() => {
    let active = true;

    const fetchDesc = async () => {
      setLoading(true);
      try {
        const res = await api.getAccessibilityDescription(
          artifactKind,
          artifactId,
        );
        if (active) {
          setDesc(res);
          setEditedText(res.description);
        }
      } catch (err) {
        showToast(
          getErrorMessage(err, 'Failed to retrieve accessibility transcript'),
        );
      } finally {
        if (active) setLoading(false);
      }
    };

    fetchDesc();
    return () => {
      active = false;
    };
  }, [artifactKind, artifactId, showToast]);

  const handleSave = async (source: 'manual' | 'reviewed') => {
    setSaving(true);
    try {
      const saved = await api.saveAccessibilityDescription({
        artifact_kind: artifactKind,
        artifact_id: artifactId,
        description: editedText,
        language: 'en',
        source,
      });
      setDesc(saved);
      showToast('Accessibility transcript updated successfully!');
    } catch (err) {
      showToast(getErrorMessage(err, 'Failed to save transcript changes'));
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-12 text-stone-400 font-mono text-[10px] gap-2">
        <Loader2 size={16} className="animate-spin text-violet-400" />
        Loading accessibility transcript...
      </div>
    );
  }

  if (!desc) return null;

  return (
    <div
      className="rounded-2xl p-6 border border-stone-850 space-y-4"
      style={{
        background: 'rgba(12, 10, 9, 0.9)',
        backdropFilter: 'blur(20px)',
        fontFamily: 'system-ui, -apple-system, sans-serif',
      }}
    >
      <div className="flex items-center justify-between border-b border-stone-800/40 pb-3">
        <div className="flex items-center gap-2">
          <FileText size={16} className="text-violet-400" />
          <h3 className="text-stone-200 text-sm font-semibold">
            Accessibility Transcript Editor
          </h3>
        </div>
        {/* Source Badge */}
        <span
          className={`text-[8px] font-mono uppercase tracking-widest px-2.5 py-0.5 rounded-full border flex items-center gap-1 ${
            desc.source === 'reviewed'
              ? 'bg-emerald-950/20 border-emerald-800/40 text-emerald-400'
              : desc.source === 'manual'
                ? 'bg-amber-950/20 border-amber-800/40 text-amber-400'
                : 'bg-violet-950/20 border-violet-800/40 text-violet-400'
          }`}
        >
          {desc.source === 'reviewed' && <ShieldCheck size={9} />}
          {desc.source === 'manual' && <CheckCircle size={9} />}
          Source: {desc.source}
        </span>
      </div>

      <div className="space-y-1.5">
        <label
          htmlFor="transcript-input"
          className="block text-[9px] uppercase tracking-[0.18em] text-stone-500 font-mono"
        >
          Interactive Screen-Reader Transcript
        </label>
        <textarea
          id="transcript-input"
          value={editedText}
          onChange={(e) => setEditedText(e.target.value)}
          rows={4}
          className="w-full rounded-xl p-3 text-xs leading-relaxed focus:outline-none transition-all resize-none bg-stone-950 border border-stone-850 text-stone-200 focus:border-violet-500/50"
          placeholder="Detailed description of parameter mappings and data trends..."
        />
        {desc.source === 'auto' && (
          <p className="text-[10px] text-stone-500 leading-snug">
            💡 <em>Notice:</em> This transcript was automatically generated by
            parsing your mapping configuration. PIs are strongly encouraged to
            review and refine descriptions before publishing.
          </p>
        )}
      </div>

      <div className="flex justify-end gap-2 pt-2 border-t border-stone-800/20">
        <button
          type="button"
          disabled={saving || editedText.trim() === ''}
          onClick={() => handleSave('manual')}
          className="flex items-center gap-1.5 rounded-full px-4.5 py-2 font-mono text-[10px] uppercase tracking-[0.2em] transition-all hover:text-stone-200 disabled:opacity-50 text-stone-400 border border-stone-800 bg-stone-900/60"
        >
          {saving ? (
            <Loader2 size={11} className="animate-spin" />
          ) : (
            <Save size={11} />
          )}
          Save Draft
        </button>
        <button
          type="button"
          disabled={saving || editedText.trim() === ''}
          onClick={() => handleSave('reviewed')}
          className="flex items-center gap-1.5 rounded-full px-5 py-2 font-mono text-[10px] uppercase tracking-[0.2em] bg-emerald-600 hover:bg-emerald-500 text-white transition-all disabled:opacity-50"
        >
          {saving ? (
            <Loader2 size={11} className="animate-spin" />
          ) : (
            <ShieldCheck size={11} />
          )}
          Approve & Publish
        </button>
      </div>
    </div>
  );
}
