#!/usr/bin/env python3
"""Reproducible audio synthesiser for the v6.2 clip library.

Reads ``api/data/clip_library.json`` and renders each clip to
``public/clips/<slug>.opus`` (96 kbps mono, consistent with the bell/source
libraries). Audio is synthesised deterministically from each clip's
``concept_tags`` so the library can be regenerated byte-for-similar on any
machine — the manifest, not the binaries, is the source of truth.

Requires ``ffmpeg`` on PATH for the Opus encode. Without it, pass ``--wav`` to
emit 16-bit PCM WAVs instead (useful for inspection / CI smoke without ffmpeg).

Usage:
    python tools/gen_clips.py                 # → public/clips/*.opus
    python tools/gen_clips.py --wav --only karplus-archetype
    python tools/gen_clips.py --bitrate 96

These are functional reference syntheses authored for AnnealMusic (license
``original-by-you``). The CC0 acoustic reference clips
(``ref-tibetan-bowl-acoustic`` etc.) are NOT synthesised here — drop the real
CC0 recordings into public/clips/ manually and record their source in
docs/AUDIO_CLIPS.md.
"""

from __future__ import annotations

import argparse
import io
import json
import math
import shutil
import struct
import subprocess
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "api" / "data" / "clip_library.json"
OUT_DIR = ROOT / "public" / "clips"
SR = 48000

# Clips supplied as real CC0 recordings rather than synthesis.
SKIP_SYNTH = {"ref-tibetan-bowl-acoustic", "ref-gong-acoustic"}


def _env(n: int, total: int, attack: float = 0.02, release: float = 0.2) -> float:
    """A simple attack/release amplitude envelope in [0, 1]."""
    t = n / total
    a = min(1.0, (n / SR) / attack) if attack > 0 else 1.0
    rel_start = 1.0 - release
    r = 1.0 if t < rel_start else max(0.0, (1.0 - t) / release)
    return a * r


def _samples(slug: str, tags: list[str], duration_ms: int):
    """Yield float samples in [-1, 1] for one clip, chosen by concept tags."""
    n_total = int(SR * duration_ms / 1000)
    tagset = set(tags)

    def sine(freq, n):
        return math.sin(2 * math.pi * freq * n / SR)

    for n in range(n_total):
        t = n / SR
        env = _env(n, n_total)
        if "beating" in tagset:
            s = 0.5 * (sine(440, n) + sine(442, n))
        elif "shepard-tone" in tagset:
            s = 0.0
            for octave in range(6):
                f = 55.0 * (2 ** octave) * (2 ** ((t / 12.0) % 1.0))
                weight = math.sin(math.pi * (octave + (t / 12.0)) / 6.0) ** 2
                s += weight * sine(f, n)
            s /= 3.0
        elif "fm" in tagset:
            ratio = 7 / 5 if "inharmonic" in tagset else (2.0 if "2:1" in tagset else 1.0)
            index = 3.0
            s = math.sin(2 * math.pi * 220 * t + index * math.sin(2 * math.pi * 220 * ratio * t))
        elif "granular" in tagset or "noise" in tagset or "comb-filter" in tagset:
            # Pseudo-random grains/noise from a deterministic LCG.
            seed = (n * 1103515245 + 12345) & 0x7FFFFFFF
            s = ((seed / 0x7FFFFFFF) * 2 - 1) * (0.6 if "dense" in tagset else 0.3)
        elif "harmonic-series" in tagset:
            partial = 1 + int((t / (duration_ms / 1000)) * 8)
            s = sine(110 * partial, n)
        elif "karplus" in tagset or "pluck" in tagset or "string" in tagset:
            decay = math.exp(-3.0 * t)
            s = decay * (sine(330, n) + 0.4 * sine(660, n))
            env = 1.0
        else:
            # Default: a warm two-partial pad.
            s = 0.7 * sine(220, n) + 0.3 * sine(440, n)
        yield max(-1.0, min(1.0, 0.6 * env * s))


def _to_wav(slug: str, tags: list[str], duration_ms: int) -> bytes:
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        frames = bytearray()
        for s in _samples(slug, tags, duration_ms):
            frames += struct.pack("<h", int(s * 32767))
        w.writeframes(bytes(frames))
    return buf.getvalue()


def _encode_opus(wav: bytes, bitrate: int) -> bytes:
    proc = subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-i", "pipe:0",
         "-ac", "1", "-c:a", "libopus", "-b:a", f"{bitrate}k", "-f", "ogg", "pipe:1"],
        input=wav, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True,
    )
    return proc.stdout


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--wav", action="store_true", help="emit WAV instead of Opus")
    ap.add_argument("--bitrate", type=int, default=96)
    ap.add_argument("--only", default=None, help="render only this slug")
    args = ap.parse_args()

    have_ffmpeg = shutil.which("ffmpeg") is not None
    if not args.wav and not have_ffmpeg:
        raise SystemExit("ffmpeg not found on PATH — install it or pass --wav")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    clips = json.loads(MANIFEST.read_text())["clips"]
    rendered = 0
    for c in clips:
        slug = c["slug"]
        if args.only and slug != args.only:
            continue
        if slug in SKIP_SYNTH:
            print(f"skip {slug} (supply the CC0 recording manually)")
            continue
        wav = _to_wav(slug, c.get("concept_tags", []), c["duration_ms"])
        ext = "wav" if args.wav else "opus"
        out = OUT_DIR / f"{slug}.{ext}"
        out.write_bytes(wav if args.wav else _encode_opus(wav, args.bitrate))
        rendered += 1
        print(f"wrote {out.relative_to(ROOT)} ({len(out.read_bytes())} bytes)")
    print(f"done: {rendered} clips → {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
