"""Authored v6.4 curriculum content — the editorial body of the slice.

This module is the single, reviewable source of the full curriculum: five
tracks, ~55 lesson specs, and the prerequisite edge list. The seed migration
(``0023``) and the end-to-end coherence test both consume it; nothing here runs
an LLM. Each lesson is authored as a :class:`LessonSpec`-shaped dict — the LLM
pipeline fills in the per-step prose at generation time.

Specs follow the field rules in ``docs/CURRICULUM_AUTHORING.md``:
  id = "{track_slug}/{lesson_slug}", track == id prefix, 1–8 objectives,
  step_outline steps carry the per-type required field (topic / patch_brief /
  task / clip_topic), and a text step may add a "diagram".

Prerequisites are expressed once, in ``PREREQ_EDGES`` (prerequisite → lesson, by
spec id), and resolved to UUIDs at seed time. The graph is a DAG rooted at
``synthesis-fundamentals/intro`` (asserted by the QA DAG check + the e2e test).
"""

from __future__ import annotations

from typing import Any

# --- Tracks ------------------------------------------------------------------

TRACKS: list[dict[str, str]] = [
    {"slug": "synthesis-fundamentals", "title": "Synthesis Fundamentals"},
    {"slug": "composition-technique", "title": "Composition Technique"},
    {"slug": "ambient-history-listening", "title": "Ambient History & Listening"},
    {"slug": "production-daw", "title": "Production & DAW"},
    {"slug": "music-science-crossover", "title": "Music + Science Crossover"},
]


# --- Authoring helpers -------------------------------------------------------

def _text(topic: str, diagram: str | None = None) -> dict[str, Any]:
    s: dict[str, Any] = {"type": "text", "topic": topic}
    if diagram:
        s["diagram"] = diagram
    return s


def _demo(patch_brief: str) -> dict[str, Any]:
    return {"type": "demo", "patch_brief": patch_brief}


def _prompt(task: str) -> dict[str, Any]:
    return {"type": "prompt", "task": task}


def _reflect(topic: str) -> dict[str, Any]:
    return {"type": "reflection", "topic": topic}


def _clip(clip_topic: str) -> dict[str, Any]:
    return {"type": "audio-clip", "clip_topic": clip_topic}


def _lesson(
    track: str,
    slug: str,
    title: str,
    objectives: list[str],
    difficulty: str,
    steps: list[dict[str, Any]],
    *,
    minutes: int = 12,
    constraints: list[str] | None = None,
    description: str | None = None,
) -> dict[str, Any]:
    return {
        "id": f"{track}/{slug}",
        "track": track,
        "title": title,
        "objectives": objectives,
        "difficulty": difficulty,
        "prerequisites": [],  # authoritative edges live in PREREQ_EDGES
        "step_outline": steps,
        "constraints_during_prompts": constraints or [],
        "estimated_minutes": minutes,
        "description": description,
    }


# --- Track 1: Synthesis Fundamentals -----------------------------------------

_T1 = "synthesis-fundamentals"
SYNTHESIS: list[dict[str, Any]] = [
    _lesson(_T1, "intro", "Intro to AnnealMusic",
        ["Understand what AnnealMusic is for", "Make your first calm sound",
         "Know how a lesson works"],
        "intro",
        [_text("what AnnealMusic is — a calm instrument for ambient music", "svg"),
         _demo("a soft, slowly evolving sine drone, gentle space"),
         _prompt("move the brightness slider and just listen"),
         _reflect("how the sound made you feel")],
        minutes=8, constraints=["brightness", "space"]),
    _lesson(_T1, "sculpt-model", "The Sculpt Model — Params, Partials, Drift",
        ["Understand params, partials, and drift as the three levers",
         "Hear how drift makes a patch feel alive"],
        "intro",
        [_text("the sculpt model: parameters shape partials, drift keeps them moving", "svg"),
         _demo("a small partial stack with audible slow drift"),
         _prompt("raise drift and notice the sound stop being static"),
         _reflect("the difference between a frozen and a drifting tone")],
        constraints=["drift", "coupling", "brightness"]),
    _lesson(_T1, "sine-engine", "The Sine Engine, Deep Dive",
        ["Understand a pure sine partial", "Hear how spread thickens a tone"],
        "intro",
        [_text("the sine engine and additive partials", "svg"),
         _clip("a single pure sine tone versus a spread stack"),
         _demo("a pure sine, then widen spread for a chorused pad"),
         _prompt("increase spread and density and listen for beating"),
         _reflect("how spread changes the character")],
        constraints=["spread", "density", "brightness"]),
    _lesson(_T1, "fm-engine", "FM — Carrier & Modulator",
        ["Understand carrier and modulator", "Hear how mod index adds harmonics"],
        "intermediate",
        [_text("frequency modulation: carrier, modulator, ratio, index", "svg"),
         _demo("a bell-like FM tone, moderate mod index"),
         _prompt("raise the modulation index and hear the spectrum brighten"),
         _reflect("how the ratio changes harmonic vs inharmonic tone")],
        constraints=["fm.modIndex", "brightness"]),
    _lesson(_T1, "granular-engine", "Granular Engine Principles",
        ["Understand grains and clouds", "Hear density and grain-size effects"],
        "intermediate",
        [_text("granular synthesis: grains, clouds, density", "svg"),
         _clip("a sparse grain cloud versus a dense one"),
         _demo("a soft granular cloud, medium density"),
         _prompt("change grain density and size and listen"),
         _reflect("how grains build a texture")],
        constraints=["density", "spread"]),
    _lesson(_T1, "physical-string", "Physical: String (Karplus–Strong)",
        ["Understand the Karplus–Strong delay loop", "Hear damping shape the decay"],
        "intermediate",
        [_text("modeling a plucked string with a delay line and damping", "svg"),
         _clip("a bright pluck versus a damped one"),
         _demo("a bright Karplus pluck"),
         _prompt("adjust damping while listening to the decay"),
         _reflect("the effect of damping on the string sound")],
        constraints=["damping", "brightness"]),
    _lesson(_T1, "physical-tube", "Physical: Tube (Waveguide)",
        ["Understand waveguide tubes", "Hear how length sets pitch and breath sets tone"],
        "intermediate",
        [_text("waveguide synthesis of tubes and pipes", "svg"),
         _demo("a soft flute-like tube tone"),
         _prompt("change tube length and breath noise"),
         _reflect("how a tube differs from a string")],
        constraints=["brightness", "drift"]),
    _lesson(_T1, "physical-plate", "Physical: Plate (Modal Banks)",
        ["Understand modal synthesis", "Hear a plate's inharmonic modes"],
        "intermediate",
        [_text("modal banks: many resonators tuned to a plate's modes", "svg"),
         _clip("a struck metal plate's shimmering decay"),
         _demo("a soft struck plate, long decay"),
         _prompt("change the modal spread and decay"),
         _reflect("why a plate sounds metallic")],
        constraints=["space", "brightness"]),
    _lesson(_T1, "physical-bowed", "Physical: Bowed Strings",
        ["Understand the bow as continuous excitation", "Hear bow pressure and speed"],
        "intermediate",
        [_text("bowed strings: stick-slip excitation", "svg"),
         _demo("a sustained bowed-string drone"),
         _prompt("vary bow pressure and listen to the timbre shift"),
         _reflect("how a bow sustains a tone a pluck cannot")],
        constraints=["brightness", "drift"]),
    _lesson(_T1, "physical-bell-glass", "Physical: Bell & Glass",
        ["Understand inharmonic bell partials", "Hear glass versus metal"],
        "intermediate",
        [_text("bells and glass: inharmonic partials and long ring", "svg"),
         _clip("a glass bell's pure ring"),
         _demo("a soft glass bell tone"),
         _prompt("change the partial stretch and decay"),
         _reflect("the difference between a bell and a glass")],
        constraints=["brightness", "space"]),
    _lesson(_T1, "physical-edge-tone", "Physical: Edge-Tone Air",
        ["Understand edge-tone excitation", "Hear breath and turbulence"],
        "advanced",
        [_text("edge tones: air splitting at an edge", "svg"),
         _demo("an airy edge-tone whistle, lots of breath"),
         _prompt("balance breath against pitch"),
         _reflect("how air noise shapes an organic tone")],
        constraints=["brightness", "drift"]),
    _lesson(_T1, "physical-mallet-membrane", "Physical: Mallet & Membrane",
        ["Understand membrane modes", "Hear mallet hardness"],
        "intermediate",
        [_text("mallets and membranes: drums and marimbas", "svg"),
         _clip("a soft mallet on a tuned bar"),
         _demo("a soft mallet tone with short decay"),
         _prompt("change mallet hardness and membrane tension"),
         _reflect("how strike material changes the attack")],
        constraints=["brightness", "damping"]),
    _lesson(_T1, "additive-engine", "Additive Engine & Spectral Tilt",
        ["Understand building tone from partials", "Hear spectral tilt brighten or darken"],
        "intermediate",
        [_text("additive synthesis and the spectral tilt control", "svg"),
         _demo("an additive pad with a gentle downward tilt"),
         _prompt("tilt the spectrum up and down"),
         _reflect("how tilt relates to brightness")],
        constraints=["brightness", "spread"]),
    _lesson(_T1, "wavetable-engine", "Wavetable Engine & Morphing",
        ["Understand wavetables", "Hear morphing between frames"],
        "intermediate",
        [_text("wavetables: scanning a table of single-cycle waves", "svg"),
         _clip("a slow morph across a wavetable"),
         _demo("a wavetable pad mid-morph"),
         _prompt("sweep the wavetable position slowly"),
         _reflect("how morphing creates motion")],
        constraints=["brightness", "drift"]),
    _lesson(_T1, "pulse-engine", "Pulse Engine & Tempo",
        ["Understand pulse-width and rate", "Hear tempo-locked pulses"],
        "intermediate",
        [_text("the pulse engine and tempo locking", "svg"),
         _demo("a slow tempo-locked pulse pad"),
         _prompt("change the pulse rate against the grid"),
         _reflect("how rhythm emerges from a pulse")],
        constraints=["speed", "brightness"]),
]


# --- Track 2: Composition Technique ------------------------------------------

_T2 = "composition-technique"
COMPOSITION: list[dict[str, Any]] = [
    _lesson(_T2, "patches-vs-pieces", "Patches vs Pieces",
        ["Distinguish a patch from a piece", "Understand when to save which"],
        "intro",
        [_text("a patch is a sound; a piece is a journey of sounds", "svg"),
         _demo("a single evolving patch as a starting point"),
         _prompt("save a patch you like, then imagine its arc"),
         _reflect("what turns a sound into a piece")]),
    _lesson(_T2, "arc-segments", "Arc Segments",
        ["Understand segments along an arc", "Hear a two-segment transition"],
        "intro",
        [_text("arcs and segments: how a piece moves over time", "svg"),
         _demo("a patch poised between two states"),
         _prompt("sketch a second segment that resolves the first"),
         _reflect("how segments give a piece shape")]),
    _lesson(_T2, "segment-types", "Open / Fixed / Transition Segments",
        ["Distinguish open, fixed, and transition segments",
         "Know when each is appropriate"],
        "intermediate",
        [_text("the three segment types and their roles", "svg"),
         _demo("a fixed segment versus an open one"),
         _prompt("place a transition between two fixed segments"),
         _reflect("why transitions matter in ambient")]),
    _lesson(_T2, "meta-arcs", "Meta-Arcs & Seeded Variation",
        ["Understand meta-arcs", "Understand seeds and reproducibility"],
        "intermediate",
        [_text("meta-arcs: arcs of arcs, and seeded variation", "svg"),
         _demo("a seeded patch that varies subtly each run"),
         _prompt("change the seed and compare two renders"),
         _reflect("how a seed balances surprise and control")]),
    _lesson(_T2, "variation-rules", "Variation Rules",
        ["Understand rule-based variation", "Constrain randomness musically"],
        "intermediate",
        [_text("variation rules: bounded, musical randomness", "svg"),
         _demo("a patch under gentle variation rules"),
         _prompt("tighten a variation rule's range"),
         _reflect("how constraints make randomness feel intentional")]),
    _lesson(_T2, "movements", "Movements",
        ["Understand movements as large sections", "Hear contrast between movements"],
        "intermediate",
        [_text("movements: the large-scale sections of a long piece", "svg"),
         _clip("a transition between two contrasting movements"),
         _demo("the opening of a calm movement"),
         _prompt("sketch a contrasting second movement"),
         _reflect("how contrast sustains a long listen")]),
    _lesson(_T2, "notation-overlay", "Notation Overlay",
        ["Read the notation overlay", "Relate notation to the sound"],
        "intermediate",
        [_text("the notation overlay and what it shows", "svg"),
         _demo("a patch with its notation overlay visible"),
         _prompt("follow the overlay as the piece plays"),
         _reflect("when notation helps and when it distracts")]),
    _lesson(_T2, "tempo-grid", "Tempo & Grid-Locking",
        ["Understand the tempo grid", "Hear grid-locked versus free timing"],
        "intermediate",
        [_text("tempo and grid-locking for loosely-timed ambient", "svg"),
         _demo("a gently grid-locked pulse pad"),
         _prompt("loosen the grid and feel the time breathe"),
         _reflect("why ambient often avoids a rigid grid")],
        constraints=["speed"]),
    _lesson(_T2, "listening-sessions", "Listening Sessions",
        ["Start a listening session", "Understand session vs piece"],
        "intro",
        [_text("listening sessions: long, low-effort playback", "svg"),
         _demo("a patch suited to a long session"),
         _prompt("start a session and step away for a minute"),
         _reflect("how a session differs from focused listening")]),
    _lesson(_T2, "drone-mode", "Drone Mode",
        ["Use drone mode", "Shape a slowly evolving drone"],
        "intro",
        [_text("drone mode: a single sustained, evolving tone", "svg"),
         _clip("a slowly evolving drone over a minute"),
         _demo("a warm evolving drone"),
         _prompt("add slow drift to keep the drone alive"),
         _reflect("what keeps a drone from feeling static")],
        constraints=["drift", "space"]),
    _lesson(_T2, "long-form", "Long-Form Composition (Album-Length)",
        ["Plan an album-length piece", "Pace energy across an hour"],
        "advanced",
        [_text("long-form: pacing energy across album lengths", "svg"),
         _demo("an opening movement designed to last"),
         _prompt("map three movements across an hour"),
         _reflect("how to keep an hour-long piece engaging")]),
    _lesson(_T2, "generative", "Generative Composition (Procedural Pieces)",
        ["Understand procedural composition", "Balance autonomy and intent"],
        "advanced",
        [_text("generative composition: pieces that compose themselves", "svg"),
         _demo("a procedural patch left to evolve"),
         _prompt("set the rules, then let the piece run"),
         _reflect("authorship when the system improvises")]),
]


# --- Track 3: Ambient History & Listening ------------------------------------

_T3 = "ambient-history-listening"
HISTORY: list[dict[str, Any]] = [
    _lesson(_T3, "origins", "Origins — Satie's Furniture Music & Cage",
        ["Know Satie's musique d'ameublement", "Understand Cage's influence on listening"],
        "intro",
        [_text("Satie's furniture music and Cage's reframing of silence"),
         _clip("a calm piece in the spirit of furniture music"),
         _prompt("listen to a patch as background, not foreground"),
         _reflect("what changes when music is furniture")]),
    _lesson(_T3, "eno-ambient-1", "Eno & \"Ambient 1\" — Naming the Genre",
        ["Know Eno's role in naming ambient", "Understand 'as ignorable as it is interesting'"],
        "intro",
        [_text("Brian Eno, Music for Airports, and the ambient manifesto"),
         _clip("a slow tape-loop-style ambient texture"),
         _prompt("make a patch that rewards both attention and inattention"),
         _reflect("Eno's balance of interesting and ignorable")]),
    _lesson(_T3, "minimalism", "Reich, Riley & Minimalism's Contribution",
        ["Know phase and process music", "Connect minimalism to ambient"],
        "intro",
        [_text("Reich's phasing, Riley's loops, and slow process"),
         _clip("two loops drifting slowly out of phase"),
         _demo("a phasing two-loop patch"),
         _prompt("set two loops slightly apart and listen for phasing"),
         _reflect("how process becomes music")]),
    _lesson(_T3, "drone-slow", "Stars of the Lid, Drone Metal & Slow Music",
        ["Know modern drone lineages", "Understand stillness as content"],
        "intermediate",
        [_text("Stars of the Lid, drone metal, and the slow-music ethos"),
         _clip("a vast, slow orchestral drone"),
         _demo("a warm, very slow drone pad"),
         _reflect("how stillness can be the content")]),
    _lesson(_T3, "japanese-ambient", "Japanese Ambient — Hosono, Yoshimura, Kankyō Ongaku",
        ["Know kankyō ongaku (environmental music)", "Recognize its spare aesthetic"],
        "intermediate",
        [_text("Japanese environmental music: Hosono, Yoshimura, Kankyō Ongaku"),
         _clip("a spare, watery Japanese-ambient miniature"),
         _demo("a sparse bell-and-water patch"),
         _reflect("space and restraint in kankyō ongaku")]),
    _lesson(_T3, "hauntology", "Hauntology & the Ghost Box School",
        ["Understand hauntology in music", "Recognize nostalgic decay"],
        "intermediate",
        [_text("hauntology, Ghost Box, and the half-remembered past"),
         _clip("a degraded, nostalgic tape texture"),
         _demo("a wow-and-flutter, aged-tape patch"),
         _reflect("why decayed media feels haunted")]),
    _lesson(_T3, "contemporary", "Contemporary Ambient — Hecker & Basinski",
        ["Know Tim Hecker and William Basinski", "Understand decay as form"],
        "intermediate",
        [_text("Tim Hecker's density and Basinski's Disintegration Loops"),
         _clip("a loop slowly disintegrating"),
         _demo("a loop patch with progressive degradation"),
         _reflect("how decay itself becomes the piece")]),
    _lesson(_T3, "modular", "Modular Synthesis & Ambient",
        ["Understand patchable modular thinking", "Relate it to AnnealMusic's sculpt model"],
        "intermediate",
        [_text("modular synthesis culture and generative patching"),
         _clip("a slowly self-modulating modular patch"),
         _demo("a self-modulating drone"),
         _reflect("the appeal of a system that surprises you")]),
    _lesson(_T3, "field-recording", "Field Recording's Place",
        ["Understand field recording in ambient", "Use environment as instrument"],
        "intermediate",
        [_text("field recording: the world as a sound source"),
         _clip("a gentle environmental field recording bed"),
         _prompt("imagine a place and the sounds that define it"),
         _reflect("how environment grounds a piece")]),
    _lesson(_T3, "new-age-vs-ambient", "New Age vs Ambient — the Messy Overlap",
        ["Distinguish new age from ambient honestly", "Avoid wellness overclaiming"],
        "intermediate",
        [_text("new age and ambient: the overlap, and honest framing of wellness claims"),
         _clip("a calm pad that sits between new age and ambient"),
         _reflect("the difference between calming and clinically effective")]),
]


# --- Track 4: Production & DAW ------------------------------------------------

_T4 = "production-daw"
PRODUCTION: list[dict[str, Any]] = [
    _lesson(_T4, "stem-export", "Stem Export Workflow",
        ["Export stems from AnnealMusic", "Understand stem naming and structure"],
        "intro",
        [_text("exporting stems: what a stem is and why it helps", "svg"),
         _demo("a layered patch worth splitting into stems"),
         _prompt("plan which layers become separate stems"),
         _reflect("when stems help and when a stereo bounce suffices")]),
    _lesson(_T4, "mixing-ambient", "Mixing Ambient Music",
        ["Apply gentle mixing to ambient", "Use headroom and slow automation"],
        "intermediate",
        [_text("mixing ambient: space, headroom, and slow moves", "svg"),
         _demo("a patch with room to breathe in the mix"),
         _prompt("balance two layers without crowding the center"),
         _reflect("why ambient mixes favor restraint")]),
    _lesson(_T4, "spatial-reverb", "Spatial Placement & Reverb",
        ["Place sounds in a stereo field", "Use reverb as an instrument"],
        "intermediate",
        [_text("spatial placement, depth, and reverb as composition", "svg"),
         _clip("a tone moving from dry to a vast reverb"),
         _demo("a patch with a long, lush reverb space"),
         _prompt("push one layer far back with reverb"),
         _reflect("how depth creates a sense of place")],
        constraints=["space"]),
    _lesson(_T4, "mastering", "Mastering for Streaming vs Vinyl",
        ["Understand loudness targets", "Know streaming vs vinyl constraints"],
        "advanced",
        [_text("mastering: loudness normalization, dynamics, and vinyl limits", "svg"),
         _demo("a finished-sounding patch to master"),
         _reflect("why ambient resists the loudness war")]),
    _lesson(_T4, "daw-integration", "AnnealMusic ↔ Logic / Ableton / Reaper",
        ["Route AnnealMusic into a DAW", "Choose audio vs MIDI workflows"],
        "intermediate",
        [_text("integrating with Logic, Ableton, and Reaper", "svg"),
         _demo("a patch to capture into a DAW session"),
         _prompt("decide audio capture versus MIDI for a part"),
         _reflect("when to leave AnnealMusic and when to stay")]),
    _lesson(_T4, "recording-sessions", "Recording Live Sessions",
        ["Capture a live performance", "Plan a take and a safety recording"],
        "intermediate",
        [_text("recording live sessions and capturing happy accidents", "svg"),
         _demo("a performable patch for a live take"),
         _prompt("rehearse one slow gesture for a take"),
         _reflect("the value of capturing imperfect performances")]),
    _lesson(_T4, "midi-out", "MIDI from AnnealMusic to Other Tools",
        ["Send MIDI to external instruments", "Map controls to CC"],
        "intermediate",
        [_text("MIDI out: notes and CC to drive other instruments"),
         _demo("a patch whose motion maps cleanly to MIDI"),
         _prompt("map a drifting control to a MIDI CC"),
         _reflect("what MIDI captures and what it loses")]),
    _lesson(_T4, "osc-basics", "OSC Integration Basics",
        ["Understand OSC vs MIDI", "Send a basic OSC message"],
        "advanced",
        [_text("OSC: high-resolution, networked control"),
         _demo("a patch driven by an external OSC source"),
         _reflect("when OSC's resolution matters")]),
]


# --- Track 5: Music + Science Crossover --------------------------------------

_T5 = "music-science-crossover"
SCIENCE: list[dict[str, Any]] = [
    _lesson(_T5, "vibrating-strings", "Physics of Vibrating Strings",
        ["Understand standing waves on a string", "Relate tension and length to pitch"],
        "intermediate",
        [_text("standing waves, nodes, and the modes of a string", "svg"),
         _clip("a string's fundamental versus its harmonics"),
         _demo("a string patch emphasizing harmonics"),
         _reflect("how physics sets a string's timbre")]),
    _lesson(_T5, "harmonic-series", "The Harmonic Series & Just Intonation",
        ["Understand the harmonic series", "Hear just intervals versus equal temperament"],
        "intermediate",
        [_text("the harmonic series and just intonation ratios", "svg"),
         _clip("a just-intonation chord versus an equal-tempered one"),
         _demo("a drone tuned to low harmonics"),
         _prompt("compare a just fifth with a tempered fifth"),
         _reflect("why just intervals sound so smooth")]),
    _lesson(_T5, "beating-roughness", "Beating, Dissonance & Roughness",
        ["Understand beating and critical bandwidth", "Hear sensory roughness"],
        "intermediate",
        [_text("beating, critical bands, and sensory dissonance", "svg"),
         _clip("two close tones beating, then widening to roughness"),
         _demo("two detuned partials beating slowly"),
         _prompt("detune two partials until they beat"),
         _reflect("the line between beating and roughness")]),
    _lesson(_T5, "phase-kuramoto", "Phase Coherence & the Kuramoto Model",
        ["Understand coupled oscillators", "Connect Kuramoto to AnnealMusic's drift"],
        "advanced",
        [_text("the Kuramoto model: how coupled oscillators synchronize", "svg"),
         _clip("partials drifting then locking into sync"),
         _demo("a coupled-oscillator patch on the edge of sync"),
         _prompt("raise coupling until the partials lock"),
         _reflect("why the drift loop feels organic")],
        constraints=["coupling", "drift"]),
    _lesson(_T5, "pitch-jnd", "Frequency, Pitch & the Just-Noticeable Difference",
        ["Distinguish frequency from pitch", "Understand the JND"],
        "intermediate",
        [_text("frequency versus perceived pitch, and the just-noticeable difference", "svg"),
         _clip("two tones a JND apart"),
         _demo("a tone you can microtune by tiny amounts"),
         _prompt("detune a tone until you can just hear the change"),
         _reflect("the limits of pitch perception")]),
    _lesson(_T5, "spectral-centroid", "Spectral Centroid & Brightness Perception",
        ["Understand spectral centroid", "Relate it to perceived brightness"],
        "intermediate",
        [_text("spectral centroid: the 'center of mass' of a spectrum", "svg"),
         _clip("a tone sweeping from dark to bright"),
         _demo("a patch you can brighten via the centroid"),
         _prompt("raise brightness and watch the centroid follow"),
         _reflect("why brightness maps to the centroid")],
        constraints=["brightness"]),
    _lesson(_T5, "onset-grouping", "Onset Detection & Temporal Grouping",
        ["Understand onsets", "Understand how we group events in time"],
        "advanced",
        [_text("onset detection and the perception of rhythm and grouping", "svg"),
         _clip("sparse onsets grouping into a perceived pulse"),
         _demo("a sparse patch with clear onsets"),
         _reflect("how the ear groups events into phrases")]),
    _lesson(_T5, "432-solfeggio", "The 432 Hz / Solfeggio Claims — Honest Framing",
        ["Understand the 432 Hz and solfeggio claims",
         "Know that the clinical evidence is absent",
         "Appreciate the real, audible timbral differences"],
        "intro",
        [_text("the 432 Hz and solfeggio claims, and what the evidence actually says"),
         _clip("a tone at 440 Hz versus 432 Hz"),
         _demo("a patch you can shift between 440 and 432 Hz"),
         _prompt("compare 440 and 432 and notice the subtle warmth"),
         _reflect("hearing a real difference without overclaiming")]),
    _lesson(_T5, "music-cognition", "Music Cognition & Ambient Listening",
        ["Understand attention and ambient listening", "Avoid wellness overclaiming"],
        "intermediate",
        [_text("how the mind attends to ambient sound — honestly framed"),
         _clip("a texture that drifts in and out of attention"),
         _reflect("how ambient can support calm without curing anything")]),
    _lesson(_T5, "resonance-modes", "Resonance, Modes & Acoustic Spaces",
        ["Understand room modes and resonance", "Relate reverb to real spaces"],
        "intermediate",
        [_text("resonance, room modes, and the acoustics of spaces", "svg"),
         _clip("a tone exciting the modes of a room"),
         _demo("a patch in a strongly resonant space"),
         _reflect("how a space becomes part of the instrument")],
        constraints=["space"]),
]


LESSONS: list[dict[str, Any]] = (
    SYNTHESIS + COMPOSITION + HISTORY + PRODUCTION + SCIENCE
)


# --- Prerequisite edges (prerequisite_id -> lesson_id), spec ids -------------
# Rooted at synthesis-fundamentals/intro. Kept acyclic (asserted by tests).

PREREQ_EDGES: list[tuple[str, str]] = [
    # Synthesis spine
    (f"{_T1}/intro", f"{_T1}/sculpt-model"),
    (f"{_T1}/sculpt-model", f"{_T1}/sine-engine"),
    (f"{_T1}/sine-engine", f"{_T1}/fm-engine"),
    (f"{_T1}/sine-engine", f"{_T1}/granular-engine"),
    (f"{_T1}/sine-engine", f"{_T1}/additive-engine"),
    (f"{_T1}/sine-engine", f"{_T1}/wavetable-engine"),
    (f"{_T1}/sculpt-model", f"{_T1}/pulse-engine"),
    (f"{_T1}/sine-engine", f"{_T1}/physical-string"),
    (f"{_T1}/physical-string", f"{_T1}/physical-tube"),
    (f"{_T1}/physical-string", f"{_T1}/physical-bowed"),
    (f"{_T1}/physical-tube", f"{_T1}/physical-plate"),
    (f"{_T1}/physical-plate", f"{_T1}/physical-bell-glass"),
    (f"{_T1}/physical-tube", f"{_T1}/physical-edge-tone"),
    (f"{_T1}/physical-plate", f"{_T1}/physical-mallet-membrane"),
    # Cross-track: harmonic series feeds the spectral engines
    (f"{_T5}/harmonic-series", f"{_T1}/fm-engine"),
    (f"{_T5}/harmonic-series", f"{_T1}/additive-engine"),
    (f"{_T1}/physical-string", f"{_T5}/vibrating-strings"),
    (f"{_T1}/sculpt-model", f"{_T5}/phase-kuramoto"),

    # Composition spine
    (f"{_T1}/intro", f"{_T2}/patches-vs-pieces"),
    (f"{_T2}/patches-vs-pieces", f"{_T2}/arc-segments"),
    (f"{_T2}/arc-segments", f"{_T2}/segment-types"),
    (f"{_T2}/segment-types", f"{_T2}/meta-arcs"),
    (f"{_T2}/meta-arcs", f"{_T2}/variation-rules"),
    (f"{_T2}/segment-types", f"{_T2}/movements"),
    (f"{_T2}/arc-segments", f"{_T2}/notation-overlay"),
    (f"{_T2}/patches-vs-pieces", f"{_T2}/tempo-grid"),
    (f"{_T1}/intro", f"{_T2}/listening-sessions"),
    (f"{_T1}/sculpt-model", f"{_T2}/drone-mode"),
    (f"{_T2}/movements", f"{_T2}/long-form"),
    (f"{_T2}/variation-rules", f"{_T2}/generative"),
    (f"{_T1}/pulse-engine", f"{_T2}/tempo-grid"),

    # History spine
    (f"{_T1}/intro", f"{_T3}/origins"),
    (f"{_T3}/origins", f"{_T3}/eno-ambient-1"),
    (f"{_T3}/origins", f"{_T3}/minimalism"),
    (f"{_T3}/eno-ambient-1", f"{_T3}/drone-slow"),
    (f"{_T3}/eno-ambient-1", f"{_T3}/japanese-ambient"),
    (f"{_T3}/eno-ambient-1", f"{_T3}/hauntology"),
    (f"{_T3}/drone-slow", f"{_T3}/contemporary"),
    (f"{_T3}/minimalism", f"{_T3}/modular"),
    (f"{_T3}/origins", f"{_T3}/field-recording"),
    (f"{_T3}/eno-ambient-1", f"{_T3}/new-age-vs-ambient"),
    (f"{_T2}/drone-mode", f"{_T3}/drone-slow"),

    # Production spine
    (f"{_T2}/patches-vs-pieces", f"{_T4}/stem-export"),
    (f"{_T4}/stem-export", f"{_T4}/mixing-ambient"),
    (f"{_T4}/mixing-ambient", f"{_T4}/spatial-reverb"),
    (f"{_T4}/mixing-ambient", f"{_T4}/mastering"),
    (f"{_T4}/stem-export", f"{_T4}/daw-integration"),
    (f"{_T2}/drone-mode", f"{_T4}/recording-sessions"),
    (f"{_T4}/daw-integration", f"{_T4}/midi-out"),
    (f"{_T4}/midi-out", f"{_T4}/osc-basics"),

    # Science spine
    (f"{_T1}/intro", f"{_T5}/harmonic-series"),
    (f"{_T5}/harmonic-series", f"{_T5}/beating-roughness"),
    (f"{_T5}/harmonic-series", f"{_T5}/vibrating-strings"),
    (f"{_T5}/beating-roughness", f"{_T5}/phase-kuramoto"),
    (f"{_T5}/harmonic-series", f"{_T5}/pitch-jnd"),
    (f"{_T1}/sine-engine", f"{_T5}/spectral-centroid"),
    (f"{_T5}/pitch-jnd", f"{_T5}/onset-grouping"),
    (f"{_T1}/intro", f"{_T5}/432-solfeggio"),
    (f"{_T5}/432-solfeggio", f"{_T5}/music-cognition"),
    (f"{_T5}/vibrating-strings", f"{_T5}/resonance-modes"),
]


def lessons_by_track() -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for lesson in LESSONS:
        out.setdefault(lesson["track"], []).append(lesson)
    return out
